language: ruby
rvm:
- 2.3.0
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database aip_development;' -U postgres
  - psql -c 'create database aip_test;' -U postgres
  - psql -c 'create database aip_production;' -U postgres
  - bin/rails db:migrate
  - bin/rails db:seed
script: bundle exec rspec
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: Q2E+1gcaN7ts/zeoiGBd6jewPSLxAQM3wrlOzPsx3Doi876Hr8N9Yz3NrljYQDyyfNt7JBPd7Di+i7qx8C10t+Uz1LkLmr1VCY1CXZD9l9T3Q34U9pMUyIp2GDFHImawKXWLnap7Tu+A+gtqYoQbDqjkaAhgnMEax5w4/Ccs+/c1Ga3dlD4ze+rGgqMW8Rg6Bd5LLrPqrud71Efce0Hg0DA2YSfX9I0EuAZPHpox5hBxELi8TYZtaiG71pwoXiMnjD+ajjVsKXy0YsqIFGYjP6gNQvwyWQIof2w4Zouf5locuLUO+uMTE1xqxpcfrJssxocRmSFBYQ79zz7ZjPPvXoYbI6+Dz15zpdcU36UjiHZOnTDYG7QqzG0Zt5alo2Ql6R1xxTfAGfH91aQNFi4I1SmwZ/SGeKDUxh0O66CYPyFubSOyTiRnXBaHWcLMRtEW3XKmZVM8kY7OsNYp7KCQcFK99fB5eX8iyKNgQd3/zaCkvBpxC9nURuUbFf/yesOsjiUKNr+rC8W+Azbzlf5jPx97n2kWIRTjqsK0Cad1gv0IaqNc5IMRvgweSlY/2GK1sYokUpq+jLK40hRd1Vyjy1lzyug2aS1xUeS4XPfy/RqRWgF9yZpa9YN47psk3cEzGLUbC6w2tQLdB13PsJcAmwvYcQFNdwJUkbdwrGSVGyU=
  app: aip
  on:
    repo: DasATeam/Agreement-Integration-Platform
